name: assignment-02

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - ./backend:/app  # Optional: for hot-reloading if you run uvicorn with --reload
    cpus: 1.0
    mem_limit: 512m

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "backend:8001"
      - "--domain=${NGROK_DOMAIN}"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"   # bang dieu khien ngrok: http://localhost:4040
    depends_on:
      - backend
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m
