"""FastAPI service for the customer-behaviour (order-satisfaction) model.

    POST /predict     one raw order  -> satisfied / dissatisfied + confidence
    POST /predict/batch
    GET  /questions   form metadata (the web + mobile clients render from this)
    GET  /samples     typical-value defaults + ~40 real example orders
    GET  /model-info  chosen model, representation, feature order
    GET  /healthz

Run:  uvicorn api.main:app --port 8000   (from customer_behaviour/)
"""
from __future__ import annotations

import json
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from . import config as C
from . import inference as I
from .schema import BatchInput, OrderInput, Prediction

_SAMPLES_PATH = Path(__file__).resolve().parent / "samples.json"


@asynccontextmanager
async def lifespan(_app: FastAPI):
    I.get_pipeline()            # fail fast if the artifact is missing
    I._explainer()             # warm the SHAP reference (feature_means.joblib)
    yield


app = FastAPI(
    title="Olist customer-behaviour — order-satisfaction prediction",
    version="1.0.0",
    description="Predicts whether a completed order will receive a positive review "
                "(review_score >= 4). Tabular behavioural features + TF-IDF of the "
                "Portuguese review comment. Model: %s (%s)." % (C.CHOSEN_MODEL, C.REPRESENTATION),
    lifespan=lifespan,
)
app.add_middleware(
    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


@app.post("/predict", response_model=Prediction, summary="Score one order")
def predict(order: OrderInput):
    try:
        return I.predict_one(order.model_dump())
    except Exception as exc:                       # noqa: BLE001
        raise HTTPException(status_code=400, detail=f"prediction failed: {exc}") from exc


@app.post("/predict/batch", summary="Score many orders")
def predict_batch(payload: BatchInput):
    try:
        return {"predictions": I.predict_batch([o.model_dump() for o in payload.orders])}
    except Exception as exc:                       # noqa: BLE001
        raise HTTPException(status_code=400, detail=f"prediction failed: {exc}") from exc


@app.get("/questions", summary="Form metadata for the web / mobile clients")
def questions():
    return {
        "fields": C.FORM_FIELDS,
        "wizard_steps": C.WIZARD_STEPS,
        "fixed_inputs": C.FIXED_INPUTS,
        "payment_types": C.PAYMENT_TYPES,
        "states": C.BRAZIL_STATES,
        "categories": C.TOP_CATEGORIES,
        "target": "satisfied (review_score >= 4)",
    }


@app.get("/samples", summary="Typical-value defaults + real example orders")
def samples():
    """`{ "defaults": {...}, "examples": [ {...order..., "_label", "_true_score"} ] }`
    Generated by `python api/make_samples.py`. Used by the web client's Quick mode
    (fills the hidden fields) and its "Load an example order" picker."""
    if not _SAMPLES_PATH.exists():
        raise HTTPException(status_code=503,
                            detail="samples.json missing — run  python api/make_samples.py")
    return json.loads(_SAMPLES_PATH.read_text(encoding="utf-8"))


@app.get("/model-info")
def model_info():
    return I.model_info()


@app.get("/healthz")
def healthz():
    try:
        I.get_pipeline()
        return {"status": "ok", "model": C.CHOSEN_MODEL}
    except Exception as exc:                       # noqa: BLE001
        raise HTTPException(status_code=503, detail=str(exc)) from exc
